version: "3.9"
services:
  dashboard:
    image: "grafana/grafana-oss:latest"
    ports:
      - 3000:3000
    volumes:
      - ./infra/config/grafana.ini:/etc/grafana/grafana.ini
      - ./infra/config/dashboards:/var/lib/grafana/dashboards
      - ./infra/config/datasources:/etc/grafana/datasources
      - ./infra/config/plugins:/var/lib/grafana/plugins
      - grafana_data:/var/lib/grafana
    user: "104"
  influx:
    image: "influxdb:latest"
    volumes:
      - influx_data:/var/lib/influxdb2:rw
    ports:
      - 8086:8086

volumes:
    grafana_data: {}
    influx_data: {}
